version: '3.2'
services:
  web:
    build: ./alpine-httpd-php-xdebug
    ports:
    - "8082:80"
    volumes:
    - ./blag:/web/html
    environment:
      XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost remote_port=9000 remote_handler=dbgp mode=req remote_autostart=1"