# docker-compose -f generate-cert-dc.yml up
version: '3.2'
services:
  cert:
    image: paulczar/omgwtfssl
    ports:
    - "8082:80"
    volumes:
    - ./certs:/certs
    environment:
      SSL_SUBJECT: "localhost"