FROM nimmis/docker-alpine-apache-php7

# tips:
# https://hub.docker.com/_/php/
# https://gist.github.com/chadrien/c90927ec2d160ffea9c4
# https://github.com/nimmis/docker-alpine-apache-php7/blob/master/Dockerfile

RUN pecl install xdebug \
&& docker-php-ext-enable xdebug